// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayersAPI.Services;

#nullable disable

namespace PlayersAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("PlayersAPI.Models.Player", b =>
                {
                    b.Property<string>("playerID")
                        .HasColumnType("TEXT");

                    b.Property<char?>("bats")
                        .HasColumnType("TEXT");

                    b.Property<string>("bbrefID")
                        .HasColumnType("TEXT");

                    b.Property<string>("birthCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("birthCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("birthDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("birthMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("birthState")
                        .HasColumnType("TEXT");

                    b.Property<int?>("birthYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("deathCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("deathCountry")
                        .HasColumnType("TEXT");

                    b.Property<int?>("deathDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("deathMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("deathState")
                        .HasColumnType("TEXT");

                    b.Property<int?>("deathYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("debut")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("finalGame")
                        .HasColumnType("TEXT");

                    b.Property<int?>("height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nameFirst")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nameGiven")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nameLast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("retroID")
                        .HasColumnType("TEXT");

                    b.Property<char?>("throws")
                        .HasColumnType("TEXT");

                    b.Property<int?>("weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("playerID");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
